language: node_js
node_js:
    - 6

env:
    global:
    - ENCRYPTION_LABEL: "9b0fc0d59948"
    - COMMIT_AUTHOR_EMAIL: "oskar@programming-php.net"

before_install:
    - gem install compass
    - npm install -g bower
    - npm install -g kss

install:
    - bower install

script:
    - bash ./travis_deploy.sh
